name: myjob

# Controls when the action will run.
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  render:
    name: Kenya Election Data update
    runs-on: ubuntu-latest
    steps:
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.1.2"
      - name: Install dependencies
        run: Rscript -e 'install.packages(c("tidyverse", "data.table", "XML", "remotes", "janitor", "rmarkdown", "DT"))'
      - name: Scrape the data
        run: Rscript R/job.R
      - name: Commit results
        run: |
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || echo "No changes to commit"
          git push origin || echo "No changes to commit"